### ISSUE TITLE
support cesium 105 

### ISSUE THREAD

**Issue by mivui** [rulonder/cesium-sensors-es6#26]
cesium use default webgl2

**Comment by rulonder** [comment]
For the time being and to keep supporting previous version I will suggest set the context to webgl1.

const viewer = new Viewer("cesiumContainer", {
  contextOptions: {
    requestWebgl1: true,
  },
});

In order to maintain backwards compatibility both webgl1 and webgl2 shaders would need to be maintained, do you know if cesium provides which context is being used?

**Comment by mivui** [comment]
```ts

const webgl = (viewer.scene as any).context._gl;
if(webgl instanceof WebGLRenderingContext){
//...
}

if(webgl instanceof WebGL2RenderingContext){
//...
}
```

**Comment by rulonder** [comment]
working with version 1.0.0 shaders updated
